version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: mongoose
    versions:
    - 5.11.14
    - 5.11.15
    - 5.11.16
    - 5.11.17
    - 5.11.18
    - 5.11.19
    - 5.12.0
    - 5.12.1
    - 5.12.2
    - 5.12.3
    - 5.12.4
    - 5.12.5
  - dependency-name: connect-mongo
    versions:
    - 3.2.0
    - 4.1.0
    - 4.2.0
    - 4.2.2
    - 4.3.0
    - 4.3.1
    - 4.4.0
  - dependency-name: bootstrap
    versions:
    - 4.5.2
  - dependency-name: bcrypt
    versions:
    - 5.0.0
  - dependency-name: jquery
    versions:
    - 3.5.1
  - dependency-name: grunt-contrib-less
    versions:
    - 2.0.0
